server:
  port: 8689

spring:
  application:
    name: transacional
  datasource:
    url: jdbc:mysql://localhost:33060/transacional?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: un_user
    password: un_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host:  localhost
    port: 5672
    username: un_user
    password: un_user

  sleuth:
    sampler:
      probability: 1.0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

crud:
  rabbitmq:
    exchanges:
      exchangeAccommodations: crud.fanout.register-accommodations
      exchangeUsers: crud.fanout.register-users
    queues:
      accommodationQueue: crud.register-accommodations.queue
      userQueue: crud.register-users.queue

ead:
  serviceRegistry:
    username: un_user
    password: 'un_user'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

info:
  app: Microsservi√ßo de Aluguel
  website: bla
  github: https://github.com/imovato

#resilience4j:
#  retry:
#    instances:
#      default:
#        max-attempts: 5
#        wait-duration: 1s
#        enable-exponential-backoff: true
#      retrySave:
#        max-attempts: 10
#        wait-duration: 1s
#        enable-exponential-backoff: true
#  ratelimiter:
#    instances:
#      default:
#        limit-for-period: 2
#        limit-refresh-period: 10s
#  bulkhead:
#    instances:
#      default:
#        max-concurrent-calls: 10
#
#  circuitbreaker:
#    instances:
#      default:
#        minimum-number-of-calls: 4
#        sliding-window-size: 8