server:
  port: 8761

spring:
  application:
    name: discovery
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cadastral
      username: un_user
      password: un_user
      auto-index-creation: true

ead:
  serviceRegistry:
    username: admin
    password: '123456'

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false